# Triggered as webhook form a netlify function
# NB!!!! this MUST be on the branch set as GitHub's default if it is to be triggered

name: Netlify Form Submission
  
on:
  repository_dispatch:
    types: [netlify-form-submission]
 
jobs:
  process-submission:
    name: Print form content
    runs-on: ubuntu-latest
    steps:
      env:
        MESSAGE: ${{ github.event.client_payload }}
      run: echo $MESSAGE
