# NB!!!! this MUST be on the branch set as GitHub's default if it is to be triggered

on:
  repository_dispatch:
    types: [netlify-form-submission]
 
jobs:
  runs-on: ubuntu-latest
  steps:
    - env:
        MESSAGE: ${{ github.event.client_payload.message }}
      run: echo $MESSAGE
